Simplify issuance backoff handling & improve error messages
cert-manager/csi-lib pull request #35
Opened 2022-09-09 14:59 UTC by munnerz

This PR changes the internals of how the NodePublishVolume calls wait for an initial issuance of a Certificate.

Previously, a volume would be registered for management in the NodePublishVolume call, and then a `wait` function was used from the driver package to wait until the manager has successfully completed an issuance of the certificate.

This made it take longer for users to see errors if there are any (it'd always take a minimum of 30s to get errors) plus it has lead to poor handling of "backing off" in cases where requests continuously fail (see #30).

Instead, the driver will now attempt *one* issuance prior to beginning the long-running renewal loop in the manager, by using the new `ManageVolumeImmediate` method. This method:

1) registers the volume as under management (to prevent any other NodePublishVolume calls that run at the same time for the volume duplicating work/interfering) but does NOT start the renewal loop
2) makes a call to `issue` to attempt a single issuance
3) if this fails, it returns so the driver can call *unmanage* and clean up volume data on disk
4) if it succeeds, it begins the renewal goroutine like usual

This allows us to lean on the kubelet/CSI driver consumer  to define the retry behaviour if a pod isn't able to start.

In cases where a *renewal* is failing, the same exponential backoff behaviour we had before will be applied (and the exponent will not be thrown away every 30s, like described in #30).

I've also tuned the exponential backoff parameters so the initial 'base' backoff in these cases is 8s, with a factor of 2 and a max cap of 5 minutes. This leads to a pattern of waiting T seconds after each attempt:

```
T=0s
T=8s
T=16s
T=32s
T=64s
T=128s
T=256s
T=300s (5 minutes, the cap)
T=300s (5 minutes, the cap)
...
```

As part of this, I've also improved the error messages returned to users in cases where their certificate requests are not being approved or issued (instead of just showing `timed out waiting for the condition`).

cc @7ing @JoshVanL

2022-09-09 15:00 UTC, munnerz commented
To note as well, the kubelet's standard backoff handling also appears to be exponential. We will rely on the kubelet to handle/time retries if a pod is in a ContainerCreating state - our own exponential backoff only comes into effect for *renewals*.

We may want to consider surfacing failed renewals via metrics in the CSI driver or something too, to make it easier for operators to identify 'stuck' renewals more easily.

2022-09-09 16:32 UTC, munnerz commented on driver/nodeserver.go
> +	ctx, _ = context.WithTimeout(ctx, time.Second*60)
I've increased this as we now return errors from approvers/issuers as soon as they happen, which makes it easier for us to tolerate issuers that take longer (as it's no longer at the cost of user experience when a failure is happening and they have to wait until this time/cap before seeing an error)

2022-09-12 09:51 UTC, JoshVanL requested changes
Thanks @munnerz, couple comments. I have walked through the state machine and the changes make sense to me.

2022-09-12 09:51 UTC, JoshVanL commented on driver/nodeserver.go
We should probably be cancelling this context on return.

```suggestion
	ctx, cancel = context.WithTimeout(ctx, time.Second*60)
        defer cancel()
```

```

2022-09-12 09:51 UTC, JoshVanL commented on manager/manager.go
> +	BackoffConfig *wait.Backoff
This is more explicit. I would always have to refer the field comment without `Renewal` prefix. 

```suggestion
	// RenewalBackoffConfig configures the exponential backoff applied to certificate renewal failures.
	RenewalBackoffConfig *wait.Backoff
```

2022-09-12 09:51 UTC, JoshVanL commented on manager/manager.go
> +			// status, however these cases are likely few and far between and this makes denial more responsive.
:+1:

2022-09-12 09:51 UTC, JoshVanL commented on manager/manager.go
> +// This
Missing rest of sentence :smile:

2022-09-12 18:00 UTC, JoshVanL commented
/lgtm

2022-09-12 18:00 UTC, merged